supportmix=/seq/vgb/linda/bin/SupportMixDistribution/Application/SupportMix
refpath=/seq/vgb/linda/mutts/Breed_tpeds_May21

$supportmix \
 --save $out'_'$chr \
 --chromosome=$chr \
 --window=$win \
 $refpath/airedale_terrier.tped \
 $refpath/akita.tped \
 $refpath/alaskan_malamute.tped \
 $refpath/australian_shepherd.tped \
 $refpath/basenji.tped \
 $refpath/basset_hound.tped \
 $refpath/beagle.tped \
 $refpath/belgian_sheepdog.tped \
 $refpath/belgian_tervuren.tped \
 $refpath/bernese_mountain_dog.tped \
 $refpath/bichon_frise.tped \
 $refpath/bloodhound.tped \
 $refpath/border_collie.tped \
 $refpath/border_terrier.tped \
 $refpath/borzoi.tped \
 $refpath/boston_terrier.tped \
 $refpath/boxer.tped \
 $refpath/brittany.tped \
 $refpath/bull_terrier.tped \
 $refpath/bulldog_english.tped \
 $refpath/bulldog_french.tped \
 $refpath/bullmastiff.tped \
 $refpath/cairn_terrier.tped \
 $refpath/cavalier_king_charles_spaniel.tped \
 $refpath/chesapeake_bay_retriever.tped \
 $refpath/chihuahua.tped \
 $refpath/chinese_crested.tped \
 $refpath/chinese_shar-pei.tped \
 $refpath/chow_chow.tped \
 $refpath/cocker_spaniel.tped \
 $refpath/collie.tped \
 $refpath/dachshund.tped \
 $refpath/dalmatian.tped \
 $refpath/doberman_pinscher.tped \
 $refpath/english_cocker_spaniel.tped \
 $refpath/english_setter.tped \
 $refpath/english_springer_spaniel.tped \
 $refpath/finnish_spitz.tped \
 $refpath/fox_terrier_wire.tped \
 $refpath/german_shepherd_dog.tped \
 $refpath/german_shorthaired_pointer.tped \
 $refpath/giant_schnauzer.tped \
 $refpath/golden_retriever.tped \
 $refpath/gordon_setter.tped \
 $refpath/great_dane.tped \
 $refpath/greater_swiss_mountain_dog.tped \
 $refpath/greyhound.tped \
 $refpath/havanese.tped \
 $refpath/irish_wolfhound.tped \
 $refpath/jack_russell_terrier.tped \
 $refpath/keeshond.tped \
 $refpath/labrador_retriever.tped \
 $refpath/leonberger.tped \
 $refpath/lhasa_apso.tped \
 $refpath/maltese.tped \
 $refpath/mastiff.tped \
 $refpath/miniature_pinscher.tped \
 $refpath/miniature_schnauzer.tped \
 $refpath/newfoundland.tped \
 $refpath/norfolk_terrier.tped \
 $refpath/norwegian_elkhound.tped \
 $refpath/norwich_terrier.tped \
 $refpath/nova_scotia_duck_tolling_retriever.tped \
 $refpath/old_english_sheepdog.tped \
 $refpath/papillon.tped \
 $refpath/pekingese.tped \
 $refpath/pembroke_welsh_corgi.tped \
 $refpath/pomeranian.tped \
 $refpath/poodle_toy.tped \
 $refpath/poodle.tped \
 $refpath/pug.tped \
 $refpath/rottweiler.tped \
 $refpath/saint_bernard.tped \
 $refpath/samoyed.tped \
 $refpath/schipperke.tped \
 $refpath/scottish_terrier.tped \
 $refpath/shetland_sheepdog.tped \
 $refpath/shih_tzu.tped \
 $refpath/siberian_husky.tped \
 $refpath/staffordshire_bull_terrier.tped \
 $refpath/tibetan_spaniel.tped \
 $refpath/vizsla.tped \
 $refpath/weimaraner.tped \
 $refpath/west_highland_white_terrier.tped \
 $refpath/whippet.tped \
 $refpath/wirehaired_pointing_griffon.tped \
 $refpath/yorkshire_terrier.tped \
 $query.tped

